# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iPjUjv03QypMNFShxiOdQfqiEr6c38C
"""

calculo = input('Olá, qual cálculo deseja fazer? ')

match calculo:
    case "somar":
        num1 = float(input("Digite o primeiro número que quer somar: "))
        num2 = float(input("Agora o segundo: "))
        soma = num1 + num2
        print(f"Resultado: {soma}")

    case "subtração":
        num1 = float(input("Digite o primeiro número que quer subtrair: "))
        num2 = float(input("Agora o segundo: "))
        sub = num1 - num2
        print(f"Resultado: {sub}")

    case "multiplicar":
        num1 = float(input("Digite o primeiro número que quer multiplicar: "))
        num2 = float(input("Agora o segundo: "))
        mult = num1 * num2
        print(f"Resultado: {mult}")

    case "dividir":
        num1 = float(input("Digite o primeiro número que quer dividir: "))
        num2 = float(input("Agora o segundo: "))
        # Verificando se o divisor é zero para evitar erro
        if num2 != 0:
            div = num1 / num2
            print(f"Resultado: {div}")
        else:
            print("Erro: Divisão por zero não é permitida.")

    case "potencia":
        num1 = int(input("Digite o número: "))
        num2 = int(input("Qual a potência: "))
        potencia = num1 ** num2
        print(f"Resultado: {potencia}")

    case _:
        print("Operação inválida.")